/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type { _ExtractParamParserType } from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    ParamParsers: never
    RouteNamedMap: import('vue-router/auto-routes').RouteNamedMap
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>, never>
    '/emoji2png': RouteRecordInfo<
      '/emoji2png',
      '/emoji2png',
      Record<never, never>,
      Record<never, never>,
      never
    >
    '/vue-welcome': RouteRecordInfo<
      '/vue-welcome',
      '/vue-welcome',
      Record<never, never>,
      Record<never, never>,
      '/vue-welcome/' | '/vue-welcome/about' | '/vue-welcome/home'
    >
    '/vue-welcome/': RouteRecordInfo<
      '/vue-welcome/',
      '/vue-welcome',
      Record<never, never>,
      Record<never, never>,
      never
    >
    '/vue-welcome/about': RouteRecordInfo<
      '/vue-welcome/about',
      '/vue-welcome/about',
      Record<never, never>,
      Record<never, never>,
      never
    >
    '/vue-welcome/home': RouteRecordInfo<
      '/vue-welcome/home',
      '/vue-welcome/home',
      Record<never, never>,
      Record<never, never>,
      never
    >
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes: '/'
      views: never
    }
    'src/pages/emoji2png.vue': {
      routes: '/emoji2png'
      views: never
    }
    'src/pages/vue-welcome.vue': {
      routes: '/vue-welcome' | '/vue-welcome/' | '/vue-welcome/about' | '/vue-welcome/home'
      views: 'default'
    }
    'src/pages/vue-welcome/index.vue': {
      routes: '/vue-welcome/'
      views: never
    }
    'src/pages/vue-welcome/about.vue': {
      routes: '/vue-welcome/about'
      views: never
    }
    'src/pages/vue-welcome/home.vue': {
      routes: '/vue-welcome/home'
      views: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info> ? Info['routes'] : keyof RouteNamedMap
}

export {}
